/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dicl_velox_VeloxDFS */

#ifndef _Included_com_dicl_velox_VeloxDFS
#define _Included_com_dicl_velox_VeloxDFS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dicl_velox_VeloxDFS
 * Method:    constructVeloxDFS
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_dicl_velox_VeloxDFS_constructVeloxDFS
  (JNIEnv *, jobject);

/*
 * Class:     com_dicl_velox_VeloxDFS
 * Method:    destructVeloxDFS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dicl_velox_VeloxDFS_destructVeloxDFS
  (JNIEnv *, jobject);

/*
 * Class:     com_dicl_velox_VeloxDFS
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_dicl_velox_VeloxDFS_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dicl_velox_VeloxDFS
 * Method:    close
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dicl_velox_VeloxDFS_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dicl_velox_VeloxDFS
 * Method:    isOpen
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dicl_velox_VeloxDFS_isOpen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dicl_velox_VeloxDFS
 * Method:    write
 * Signature: (JJ[BJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_dicl_velox_VeloxDFS_write
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     com_dicl_velox_VeloxDFS
 * Method:    read
 * Signature: (JJ[BJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_dicl_velox_VeloxDFS_read
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     com_dicl_velox_VeloxDFS
 * Method:    getMetadata
 * Signature: (J)Lcom/dicl/velox/model/Metadata;
 */
JNIEXPORT jobject JNICALL Java_com_dicl_velox_VeloxDFS_getMetadata
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dicl_velox_VeloxDFS
 * Method:    remove
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dicl_velox_VeloxDFS_remove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dicl_velox_VeloxDFS
 * Method:    exists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dicl_velox_VeloxDFS_exists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dicl_velox_VeloxDFS
 * Method:    list
 * Signature: (ZLjava/lang/String;)[Lcom/dicl/velox/model/Metadata;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dicl_velox_VeloxDFS_list
  (JNIEnv *, jobject, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
