/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class velox_VDFS */

#ifndef _Included_velox_VDFS
#define _Included_velox_VDFS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     velox_VDFS
 * Method:    constructVDFS
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_velox_VDFS_constructVDFS
  (JNIEnv *, jobject);

/*
 * Class:     velox_VDFS
 * Method:    destructVDFS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_velox_VDFS_destructVDFS
  (JNIEnv *, jobject);

/*
 * Class:     velox_VDFS
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_velox_VDFS_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     velox_VDFS
 * Method:    close
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_velox_VDFS_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     velox_VDFS
 * Method:    isOpen
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_velox_VDFS_isOpen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     velox_VDFS
 * Method:    write
 * Signature: (J[BJJ)J
 */
JNIEXPORT jlong JNICALL Java_velox_VDFS_write
  (JNIEnv *, jobject, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     velox_VDFS
 * Method:    read
 * Signature: (J[BJJ)J
 */
JNIEXPORT jlong JNICALL Java_velox_VDFS_read
  (JNIEnv *, jobject, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     velox_VDFS
 * Method:    getMetadata
 * Signature: (J)Lvelox/model/Metadata;
 */
JNIEXPORT jobject JNICALL Java_velox_VDFS_getMetadata
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
