/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class velox_VeloxDFS */

#ifndef _Included_velox_VeloxDFS
#define _Included_velox_VeloxDFS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     velox_VeloxDFS
 * Method:    constructVeloxDFS
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_velox_VeloxDFS_constructVeloxDFS
  (JNIEnv *, jobject);

/*
 * Class:     velox_VeloxDFS
 * Method:    destructVeloxDFS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_velox_VeloxDFS_destructVeloxDFS
  (JNIEnv *, jobject);

/*
 * Class:     velox_VeloxDFS
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_velox_VeloxDFS_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     velox_VeloxDFS
 * Method:    close
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_velox_VeloxDFS_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     velox_VeloxDFS
 * Method:    isOpen
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_velox_VeloxDFS_isOpen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     velox_VeloxDFS
 * Method:    write
 * Signature: (JJ[BJJ)J
 */
JNIEXPORT jlong JNICALL Java_velox_VeloxDFS_write
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     velox_VeloxDFS
 * Method:    read
 * Signature: (JJ[BJJ)J
 */
JNIEXPORT jlong JNICALL Java_velox_VeloxDFS_read
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     velox_VeloxDFS
 * Method:    getMetadata
 * Signature: (J)Lvelox/model/Metadata;
 */
JNIEXPORT jobject JNICALL Java_velox_VeloxDFS_getMetadata
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
