/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class velox_VeloxDFS */

#ifndef _Included_velox_VeloxDFS
#define _Included_velox_VeloxDFS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     velox_VeloxDFS
 * Method:    constructDFS
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_velox_VeloxDFS_constructDFS
  (JNIEnv *, jobject);

/*
 * Class:     velox_VeloxDFS
 * Method:    destructDFS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_velox_VeloxDFS_destructDFS
  (JNIEnv *, jobject);

/*
 * Class:     velox_VeloxDFS
 * Method:    format
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_velox_VeloxDFS_format
  (JNIEnv *, jobject);

/*
 * Class:     velox_VeloxDFS
 * Method:    exists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_velox_VeloxDFS_exists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     velox_VeloxDFS
 * Method:    touch
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_velox_VeloxDFS_touch
  (JNIEnv *, jobject, jstring);

/*
 * Class:     velox_VeloxDFS
 * Method:    write
 * Signature: (Ljava/lang/String;[CJJ)J
 */
JNIEXPORT jlong JNICALL Java_velox_VeloxDFS_write
  (JNIEnv *, jobject, jstring, jcharArray, jlong, jlong);

/*
 * Class:     velox_VeloxDFS
 * Method:    read
 * Signature: (Ljava/lang/String;[CJJ)J
 */
JNIEXPORT jlong JNICALL Java_velox_VeloxDFS_read
  (JNIEnv *, jobject, jstring, jcharArray, jlong, jlong);

/*
 * Class:     velox_VeloxDFS
 * Method:    getMetadata
 * Signature: (Ljava/lang/String;)Lvelox/model/Metadata;
 */
JNIEXPORT jobject JNICALL Java_velox_VeloxDFS_getMetadata
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
